# window:
  # opacity: 0.75
font:
  size: 12
  normal:
    family: Azeret Mono
    style: Regular
  italic:
    family: Azeret Mono
    style: Italic
  bold:
    family: Azeret Mono
    style: Bold
mouse:
  hide_when_typing: true


colors:
  primary:
    background: "#052429"
    foreground: "#D0C0A0"
    dim_foreground: "#D0C0A0"
